version: '3.8'

services:
  db:
    image: postgres:16.2-alpine3.19
    container_name: everest_db
    environment:
      - POSTGRES_DB=everest_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=8581
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d everest_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: everest_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/everest_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=8581
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - STORAGE_LOCATION=/app/uploads
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile_front
    container_name: everest_frontend
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data: